### ISSUE TITLE
Problems installing with pip

### ISSUE THREAD

**Issue by Zweitze** [mjj4791/python-buienradar#6]
Using install with pip gives:
```
(env)>pip install buienradar
Collecting buienradar
  Using cached https://files.pythonhosted.org/packages/09/ec/7f533e5c8794aa591d7652ca30bd8f8fbdc53175b3641d00173068be2de6/buienradar-1.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    fatal: not a git repository (or any of the parent directories): .git
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\zweitze\AppData\Local\Temp\pip-install-e6ub_f9z\buienradar\setup.py", line 29, in <module>
        version=version_from_git(),
      File "C:\Users\zweitze\AppData\Local\Temp\pip-install-e6ub_f9z\buienradar\setup.py", line 23, in version_from_git
        universal_newlines=True)
      File "c:\python36\Lib\subprocess.py", line 356, in check_output
        **kwargs).stdout
      File "c:\python36\Lib\subprocess.py", line 438, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['git', 'describe', '--tags', '--abbrev=0']' returned non-zero exit status 128.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\zweitze\AppData\Local\Temp\pip-install-e6ub_f9z\buienradar\
```

I'm using pip 19.0.3 and Python 3.6.8
Similar problems occur when installing with requirements.txt. Version 0.91 does not have this problem.

**Comment by mjj4791** [comment]
I have pushed a new version of the library (1.0.1), which should fix this.
